---
title: "Example 02 Standard deviations"
author: "Sergio Diez-Hermano"
date: '`r Sys.Date()`'
output:
  html_document:
      highlight: tango
      toc: yes
      toc_depth: 4
      toc_float:
        collapsed: no
---

```{r setup, include=FALSE}
require(knitr)
# include this code chunk as-is to set options
opts_chunk$set(comment = NA, prompt = FALSE, fig.height=5, fig.width=5, dpi=300, fig.align = "center", echo = TRUE, message = FALSE, warning = FALSE, cache=FALSE)
Sys.setlocale("LC_TIME", "C")
```

# Libraries and functions

```{r}
library(tictoc)
library(data.table)
library(dplyr)
library(tidyr)
library(pbapply)
library(ggplot2)
library(stringr)
library(patchwork)
library(viridis)

# Similarity structure
library(similaritystructure)

```

# Similarity structure

DON'T RUN! Run only to replicate the procedure

```{r, eval = F}
# Parameters
sd_shift <- seq(1.05, 2, 0.05)
alpha <- 0.05
N_init <- 2
# For each value of the std, the subsample size N changes to optimize the computation times:
N_fin <- c(30000, 12000, 6000, 4000, 2500, 1700, 1200, 1000, 800, 
           700, 600, 550, 500, 500, 400, 350, 300, 300, 250, 250)
num_N <- 60       # Number of equidistant subsample sizes
num_repet <- 300  # Number of tests per subsample size

# Randomization and smooth
seed <- 12345

# Generate random sample
set.seed(seed)
n1 <- rnorm(30000, 0, 1)

tic()
ssmany <- pblapply(1:length(sd_shift), 
                   function(x) similarity_structure(n1, n1*sd_shift[x], 
                                                    N_init, 
                                                    N_fin = N_fin[x], 
                                                    num_N, num_repet, 
                                                    test = "ks-test", 
                                                    alpha = alpha,
                                                    sav = FALSE, 
                                                    # sav_file = paste0("sdshift_", x, ".RData"),
                                                    plotting = T,
                                                    seed = seed,
                                                    title_plot = paste0("SD shift: ", sd_shift[x])))
toc()
names(ssmany) <- sd_shift

# saveRDS(ssmany, "example_02_ks.RData")

```

## Plot fitting and smoothing

```{r, fig.height=20, fig.width=30}
# Load similarity structures
# Change "example_01_ks" to "example_01_ttest"
filename <- system.file("extdata", "example_02_ks.RData", package = "similaritystructure")
datafile <- readRDS(filename)
sd_shift <- seq(1.05, 2, 0.05)

par(mfrow = c(4, 6), mar = c(4, 4, 2, 0.3), bg = "gray", cex = 1.2)

for (i in sd_shift) {
  
  plotdata <- datafile[[as.character(i)]]
  propsig <- plotdata$empiric_PNalpha
  smoothdata <- plotdata$simil_struct_Ns$smooth
  fitdata <- plotdata$simil_struct_Ns$fitting
  
  plot(propsig$N, propsig$scaled, type = 'l', col = "black",lwd=1.5, 
       ylab = "Scaled g(n)", xlab = "Subsample size",
       main = paste0("SD shift: ", i))
  lines(fitdata$vect_N_fit, fitdata$Scale*fitdata$fun_fit, type = 'l', col = "darkred",lwd=1.5)
  lines(smoothdata$vect_N_smooth, smoothdata$fun_smooth, col = "darkgreen")
  abline(v = 0, lty = "dashed")
  abline(v = fitdata$Ns_fitting, col = "darkred")
  abline(v = smoothdata$Ns_smooth, col = "darkgreen")
  legend("topright", c("Fitting", "Smooth"), col = c("darkred", "darkgreen"), lty = "solid")
  
}

```


# Plot all p(n)

```{r, fig.width=10, fig.height=5}
# Load similarity structures
filename <- system.file("extdata", "example_02_ks.RData", package = "similaritystructure")
datafile <- readRDS(filename)
sd_shift <- seq(1.05, 2, 0.05)

jet <- function(n) {
  colorRampPalette(c(
    "#00007F", "blue", "#007FFF", "cyan",
    "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000"
  ))(n)
}

cols <- jet(length(datafile))
names(cols) <- sd_shift

# Plot
par(mfrow = c(1,2), mar = c(4, 4, 2, 0.3), bg = "gray", cex = 1.2)

# Fitting
plot(0, 0, xlim = c(log10(2), log10(20000)), ylim = c(0, 0.015), type = "n", xaxt = "n",
     ylab = "p(n)", xlab = "Subsample size", 
     main = "Fitting")
axis(1, at = c(1, 2, 3, 4),
     labels = expression(10^1, 10^2, 10^3, 10^4))

for (i in rev(sd_shift)) {
  
  plotdata <- datafile[[as.character(i)]]
  logN <- plotdata$simil_struct_Ns$fitting$vect_N_fit %>% log10()
  fitdata <- plotdata$simil_struct_Ns$fitting$P_N_alpha
  
  lines(logN, fitdata, type = 'l', col = cols[as.character(i)], lwd=1.5)

}

# Smoothing
plot(0, 0, xlim = c(log10(2), log10(20000)), ylim = c(0, 0.015), type = "n", xaxt = "n",
     ylab = "p(n)", xlab = "Subsample size", 
     main = "Smooth")
axis(1, at = c(1, 2, 3, 4),
     labels = expression(10^1, 10^2, 10^3, 10^4))

for (i in rev(sd_shift)) {
  
  plotdata <- datafile[[as.character(i)]]
  logN <- plotdata$simil_struct_Ns$smooth$vect_N_smooth %>% log10()
  fitdata <- plotdata$simil_struct_Ns$smooth$fun_smooth_norm
  
  lines(logN, fitdata, type = 'l', col = cols[as.character(i)], lwd=1.5)

}

```

# Probability of effect

```{r}
# Load similarity structures
filename <- system.file("extdata", "example_02_ks.RData", package = "similaritystructure")
datafile <- readRDS(filename)

pares <- combn(seq_along(datafile), 2)

ps_list <- apply(pares, 2, 
                 function(i) {prob_effect(datafile[[i[1]]]$simil_struct_Ns$fitting, 
                                          datafile[[i[2]]]$simil_struct_Ns$fitting,
                                          datafile[[i[1]]]$simil_struct_Ns$smooth,
                                          datafile[[i[2]]]$simil_struct_Ns$smooth)})

names(ps_list) <- apply(pares, 2, 
                        function(i) {paste(names(datafile)[i[1]], names(datafile)[i[2]], sep = "_vs_")})

```

## Plot

```{r, fig.height=5, fig.width=10}
# List to data frame
ps_df <- tibble(
  comparacion = names(ps_list),
  ps_fit = sapply(ps_list, \(x) x$ps_fit),
  ps_smooth = sapply(ps_list, \(x) x$ps_smooth)
) %>%
  separate(comparacion, into = c("m1", "m2"), sep = "_vs_") %>%
  mutate(
    m1 = as.numeric(m1),
    m2 = as.numeric(m2)
  )

# Prepare data for plotting as a symmetric matrix
# Duplicate data frame 
ps_df_sym <- bind_rows(
  ps_df,
  ps_df %>%
    rename(m1 = m2, m2 = m1)
)

# Sort std differences
valores_m <- sort(unique(c(ps_df$m1, ps_df$m2)))

# Add diagonal, if 1:
# diag_df <- tibble(
#   m1 = valores_m,
#   m2 = valores_m,
#   ps_fit = 1,
#   ps_smooth = 1
# )

# If empty:
diag_df <- tibble(
  m1 = valores_m,
  m2 = valores_m,
  ps_fit = NA_real_,
  ps_smooth = NA_real_
)

ps_plot <- bind_rows(ps_df_sym, diag_df) %>%
  mutate(
    m1 = factor(m1, levels = valores_m),
    m2 = factor(m2, levels = valores_m)
  )

# Same color range for fitting and smoothing
rango <- range(c(ps_plot$ps_fit, ps_plot$ps_smooth), na.rm = TRUE)
# rango <- c(0, 0.5)

# Plotting
plot_heatmap <- function(data, variable, titulo = NULL) {
  
  ggplot(data, aes(x = m1, y = m2, fill = .data[[variable]])) +
    geom_tile() +
    coord_equal() +
    scale_fill_viridis_c(
      name = variable,
      limits = rango,
      na.value = "yellow"
    ) +
    labs(
      x = "m",
      y = "m",
      title = titulo
    ) +
    theme_bw() +
    theme(
      panel.grid = element_blank(),
      axis.text.x = element_text(angle = 45, hjust = 1)
    )
}

p_fit <- plot_heatmap(ps_plot, "ps_fit", "ps_fit")
p_smooth <- plot_heatmap(ps_plot, "ps_smooth", "ps_smooth")

p_fit + p_smooth

```

